[package]
name = "benchmarks"
version = "0.1.0"
authors = ["Doug Hodson <doug@sidechannel.net>"]
edition = "2018"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false
